import React from 'react';

const Terms = () => {



    return (
        <><h1>OPERATING AGREEMENT FOR HAPPY MASK SHOP,
            A Michigan Limited Liability Company
        </h1><p>THIS OPERATING AGREEMENT is made and entered into on 3/1/2022, by and among Happy Mask Shop, a Michigan limited
            liability company, and each of those Persons executing this Operating Agreement as a member, all of whom agree as
            follows:</p><h2>ARTICLE I
                ORGANIZATION
            </h2><p><b>1.1 Formation.</b> The Company has been organized as a (manager-managed or member – managed) Michigan limited
                liability company by the filing of Articles of Organization (the Articles) as required by the Michigan Limited
                Liability Company Act (the Act), MCL 450.4101 et seq.</p><p><b>1.2 Name.</b> The name of the Company is stated on the first page of this Operating Agreement. The Company may
                    also conduct its business under one or more assumed names.
            </p><p><b>1.3 Purpose.</b> The Company has been formed for the purpose or purposes enumerated in the Articles. The Company shall
                have all the powers necessary or convenient to affect any purpose for which it is formed, including all powers
                granted by the Act.</p>
            <p><b>1.4 Duration.</b> The Company shall commence on the date of filing of the Articles with Department of Labor and Economic Growth, Bureau of Commercial Services (the Bureau), and shall continue in existence for the period fixed in the Articles or until the Company dissolves and its affairs are wound up in accordance with the Act or this Operating Agreement.</p>
            <p><b>1.5 Registered Office and Resident Agent.</b> The Registered Office and the Resident Agent of the Company shall be as designated in the initial, restated, or amended Articles. The Registered Office and the Resident Agent may be changed from time to time. Any such change shall be made in accordance with the requirements of the Act. If the Resident Agent resigns, the Company shall promptly appoint a successor.
            </p>
            <p><b>1.6 No Liability of Managers and Members.</b> Unless otherwise provided by law or in this Operating Agreement, a person who is a member, a manager, or both of the Company is not liable for the acts, debts, or obligations of the Company.</p>
            <p><b>1.7 Management.</b> The business of the Company shall be managed by or under the authority of managers as provided in Article VII of this Operating Agreement. OR  The business of the Company shall be managed by or under the authority of members as provided in Article VII of this Operating Agreement.</p>
            <p><b>1.8 Admission of New Members.</b> The Members may, on the (unanimous OR majority OR Supermajority vote of ___%) vote of the Members entitled to vote, admit as a Member any person determined by the Members to satisfy the criteria established by the Members, in their sole and absolute discretion, for membership in the Company. The person shall, before being admitted as a Member of the Company and as a condition to it, execute any documents required by the Company, agreeing to be and become a Member of the Company, subject to all of the terms and conditions of this Operating Agreement. The Company may issue additional shares (Shares) in the Company to new Members on any terms and conditions and for any consideration, if any, that the Members determine.</p>
            <p><b>1.9 No Right of Withdrawal.</b> The Members shall not have any right of withdrawal or any right to receive any payment or distribution from the Company on any actual or purported withdrawal. The Members agree not to withdraw, and they waive any right of withdrawal and any right to receive any payment or distribution on withdrawal provided for or under the Act.</p>
            <h2>ARTICLE II
                ADMINISTRATIVE PROVISIONS
            </h2>
            <p><b>2.1 Books of Account.</b> At all times during the continuance of the Company, the Company shall keep or cause to be kept full and true books of account reflecting each of the Company’s transactions. These books of account, together with a list of the name and address of each Member; a copy of the Articles; copies of the Company’s financial statements and federal, state, and local tax returns and reports for the three most recent fiscal years; a copy of this Operating Agreement; and copies of records that would enable a Member to determine the Member’s Shares shall be maintained at all times at the Company’s registered office. These books shall be open to reasonable inspection and examination by the Members at the Company’s registered office, during reasonable business hours, on reasonable notice to the Company. The Company may engage certified public accountants to assist in the preparation of the Company’s books and financial statements and to render any other services the Company requests.</p>
            <p><b>2.2 Reports.</b> The Company shall furnish to each Member within 90 days after the end of each fiscal year, or as soon as practical after that, an annual report of the Company’s business and operations during the year, together with whatever information is necessary for the preparation of each Member’s federal and state income or other tax returns. The annual report shall contain a copy of the Company’s annual financial statement showing the Company’s gross receipts and expenses and profit or loss and their allocation to each Member for the year.</p>
            <p><b>2.3 Fiscal Year and Accounting Method.</b> The fiscal year of the Company shall be (the calendar year OR from ___________ to ____________. The Company’s books and records shall be kept on a(n) (cash OR accrual method) as determined by the (Managers OR Members).</p>
            <p><b>2.4 Checks.</b> All checks, drafts, orders for the payment of money, notes, or evidences of indebtedness issued in the name of the Company shall be signed by a (Manager OR Member) or an agent of the Company and in a manner determined by the (Managers or Members).</p>
            <h2>ARTICLE III
                CAPITAL CONTRIBUTIONS, MEMBERSHIP SHARES,
                AND CAPITAL ACCOUNTS
            </h2>
            <p><b>3.1 Capital Contributions and Membership Interests.</b> By executing this Operating Agreement, the Members agree to make the capital contributions set forth in the attached Exhibit A. Each Member owns a membership interest in the Company, represented by the Member’s Shares in the Company set forth in Exhibit A. Any additional Member (other than an assignee of a membership interest who has been admitted as a Member) shall make the capital contribution required in a written agreement with the Company and the other Members concerning the additional Member’s admission as a Member.</p>
            <p><b>3.2 Additional Contributions.</b> In addition to the initial capital contributions, the (Managers OR Members) may determine from time to time that additional capital is needed to enable the Company to conduct its business and affairs. After making such a determination, notice of it shall be given to all Members in writing at least 30 days before the date on which the additional contributions are due. The notice shall describe, in reasonable detail, the purposes and uses of the additional capital, the amounts of additional capital required, and the date by which payment of the additional capital is due. Each Member’s percentage of the total additional capital due shall equal the percentage of each Member’s Shares to the total Shares in the Company.</p>
            <p><b>3.3 Failure to Contribute.</b>If a Member fails to make a capital contribution when required, the Company may, in addition to pursuing any other rights and remedies the Company may have under the Act or applicable law, take any enforcement action (including the commencement and prosecution of court proceedings) against the Member that the (Managers OR Members) consider appropriate. Moreover, the remaining Members may elect to contribute the required capital themselves, according to their respective Shares. The Members who make such contributions shall be entitled to treat these amounts as an extension of credit to the defaulting Member, payable on demand, with interest accruing on the extension at the rate of [percentage, stay within legal rates] per annum until paid. This extension of credit shall be secured by the defaulting Member’s interest in the Company. Each Member, who defaults, grants to each Member who may later make an extension of credit a security interest in the defaulting Member’s interest in the Company.</p>
            <p><b>3.4 Capital Accounts.</b> The company shall maintain a separate capital account for each Member (the Capital Accounts). Each Capital Account shall be</p>
            <ul>a. increased (i) for the amount of cash and the fair market value of any property (net of any liabilities secured by the property that the Company assumes or takes subject to) that the Member contributes and (ii) for the Member’s Share of any of the Company’s income or gain and
            </ul>
            <ul>b. decreased (i) for the amount of any cash and the fair market value of any property (net of any liabilities secured by the property that the Company assumes or takes subject to) distributed to the Member, (ii) for the Member’s Share of any losses and deductions of the Company, and (iii) for any expenditures under IRC 705(a)(2)(B).
            </ul>
            <p>If a Member’s Shares, or any portion of them, are transferred in accordance with this Operating Agreement, the transferee shall succeed to the Capital Account of the transferring Member or to any portion that is transferred. All of the provisions of this section regarding the establishment and maintenance of Capital Accounts are intended to comply with Treasury Regulation 1.704-1(b)(2)(iv) and shall be interpreted and applied to comply with the Treasury Regulation. The Members agree to make any adjustment to the Capital Accounts that may be necessary or appropriate to comply with the Treasury Regulation.</p>

            <h2>ARTICLE IV
                ALLOCATIONS AND DISTRIBUTIONS
            </h2>
            <p><b>4.1 Allocations.</b> Except as may be required by the Internal Revenue Code (IRC) or by this Operating Agreement, the Company’s net profits, net losses, and other items of income, gain, loss, deduction, and credit shall be allocated among the Members first, so their Capital Account balances are, as nearly as possible, in the same ratios as their respective Shares, and then, pro rata, in accordance with the Shares held by each Member. </p>
            <p><b>4.2 Distributions.</b> The (Managers OR Members) may make distributions to the Members from time to time. Distributions may be made only after the (Managers OR Members) determine, in their reasonable judgment, that the Company has cash on hand exceeding the Company’s current and anticipated needs (including operating expenses, debt service, acquisitions, reserves, and mandatory distributions, if any). All distributions shall be made to the Members in accordance with each Member’s Shares. Distributions shall be in cash, property, or both, as the (Managers OR Members) determine. No distribution shall be declared or made if, after giving it effect, (a) the Company would not be able to pay its debts as they became due in the usual course of business or (b) the Company’s total assets would be less than the sum of its total liabilities plus the amount that would be needed, if the Company were to be dissolved at the time of the distribution, to satisfy on dissolution the preferential rights of other Members that are superior to the rights of the Members receiving the distribution. The (Managers OR Members) shall endeavor to make distributions in cash to the Members at times and in amounts that enable the Members to pay the tax due on the income of the Company before its due date.</p>
            <h2>ARTICLE V
                DISPOSITION OF SHARES
            </h2>
            <p><b>5.1 General.</b> Each Member shall have the power, without the consent of other Members, to substitute for themselves in the Company a person who is not a Member of the Company. This substitution shall confer on the substituted Member all the attributes of the transferring Member’s Shares in the Company. The person shall be admitted as a substitute Member and shall be entitled to all the rights and powers of a Member. The substitute Member shall also then be subject to all the restrictions and liabilities of a Member.
            </p>
            <h2>ARTICLE VI
                VOTING OF MEMBERS
            </h2>
            <p><b>6.1 Voting.</b> All Members shall be entitled to vote on any matter submitted to a vote of the Members. The Members shall have the right to vote on all of the following: (a) the dissolution of the Company; (b) the merger of the Company; (c) an amendment to the Articles; and (d) the sale of all or substantially all of the Company’s assets other than in the ordinary course of business.</p>
            <p><b>6.2 Required Vote.</b> Unless a greater vote is required by the Act or the Articles, the affirmative vote of a majority of the Shares of all the Members entitled to vote on a matter is required.</p>
            <p><b>6.3 Meetings.</b> An annual meeting of Members for the transaction of whatever business properly comes before the meeting shall be held at the time, date, and place that the Managers shall determine. Special meetings of Members for any proper purpose or purposes may be called at any time by the Managers or the holders of at least 10 percent of the Shares of all Members entitled to vote. The Company shall deliver or mail written notice stating the date, time, place, and purposes of any meeting to each Member entitled to vote at the meeting. The notice shall be given not less than 10 or more than 60 days before the meeting date. All meetings of Members shall be presided over by a chairperson, designated by the Managers from among themselves.</p>
            <p><b>6.4 Consent.</b> Any action required or permitted to be taken at an annual or special meeting of the Members may be taken by consent or approval without a meeting or prior notice. The consent or approval must be in writing, set forth the action to be taken, and be signed by the Members having at least the minimum number of votes necessary to authorize or take the an action at a meeting at which all membership interests entitled to vote on the action are present and voting. Every written consent or approval shall also bear the date of when each Member signed the consent. Prompt notice of the taking of action without a meeting by less than unanimous written consent of the Members entitled to vote shall be given to all Members who did not consent to or approve the action.
            </p>
            <h2>ARTICLE VII
                MANAGEMENT
            </h2>
            <p><b>7.1 Management of Business.</b> The Company shall be managed by no fewer than [number] and no more than [number] persons Managers , who shall be designated by resolution of the Members. The Members shall determine the Managers’ terms, duties, compensation, and benefits, if any. The Managers shall serve at the will and pleasure of the Members.</p>
            <p><b>7.2 General Powers of Managers.</b> Except as may otherwise be provided in this Operating Agreement, the ordinary and usual decisions concerning the business and affairs of the Company shall be made by the managers. Each Manager has the power, on behalf of the Company, to do all things necessary or convenient to carry out the Company’s business and affairs, including the power to (a) purchase, lease, or otherwise acquire any real or personal property; (b) sell, convey, mortgage, grant a security interest in, pledge, lease, exchange, or otherwise dispose of or encumber any real or personal property; (c) open one or more depository accounts and make deposits into, write checks against, and make withdrawals against the accounts; (d) borrow money and incur liabilities and other obligations; (e) enter into any and all agreements and execute any and all contracts, documents, and instruments; (f) engage employees and agents and define their respective duties and compensation; (g) establish pension plans, trusts, profit-sharing plans, and other benefit and incentive plans for Members, employees, and agents of the Company; (h) obtain insurance covering the business and affairs of the Company and its property and on the lives and well-being of its Members, employees, and agents; (i) begin, prosecute, or defend any proceeding in the Company’s name; and (j) participate with others in partnerships, joint ventures, and other associations and strategic alliances.
            </p>
            <p><b>7.3 Limitations.</b> Notwithstanding any other provision of this Operating Agreement, no act shall be taken, sum expended, decision made, obligation incurred, or power exercised by any Manager on behalf of the Company, except by the (unanimous OR other vote of majority or greater) consent of all Members, with respect to (a) any significant and material purchase, receipt, lease, exchange, or other acquisition of any real or personal property or business; (b) the sale of all or substantially all of the assets and property of the Company; (c) any mortgage, grant of security interest, pledge, or encumbrance on all or substantially all of the assets and property of the Company; (d) any merger; (e) any amendment or restatement of the Articles or this Operating Agreement; (f) any matter that could result in a change in the amount or character of the Company’s capital; (g) any change in the character of the business and affairs of the Company; (h) the commission of any act that would make it impossible for the Company to carry on its ordinary business and affairs; or (i) any act that would contravene any provision of the Articles, Operating Agreement, or the Act.</p>
            <p><b>7.4 Standard of Care; Liability.</b> Every Manager shall discharge his or her duties as a manager in good faith, with the care an ordinarily prudent person in a like position would exercise under similar circumstances, and in a manner the Manager reasonably believes to be in the best interests of the Company. A Manager shall not be liable for any monetary damages to the Company for any breach of duty except for (a) receipt of a financial benefit to which the Manager is not entitled, (b) voting for or assenting to a distribution to Members in violation of this Operating Agreement or the Act, or (c) a knowing violation of the law.</p>
            <h2>ARTICLE VIII
                INDEMNIFICATION
            </h2>
            <p><b>8.1 Exculpation of Liability.</b> Unless otherwise provided by law or expressly assumed, a person who is a Member, a Manager, or an Officer or any combination shall not be liable for the acts, debts, or liabilities of the Company.</p>
            <p><b>8.2 Indemnification.</b> The Company shall indemnify, defend, and hold each Member, Manager, or Officer harmless from and against any losses, claims, costs, damages, and liabilities, including, without limitation, judgments, fines, amounts paid in settlement, and expenses (including, without limitation, attorney fees and expenses, court costs, investigation costs, and litigation costs) incurred by any Member in any civil, criminal, or investigative proceeding in which it is involved or threatened to be involved by reason of the party being a Member of the Company provided that the Member acted in good faith, within what he or she reasonably believed to be the scope of his or her authority, for a purpose that he or she reasonably believed to be in the best interests of the Company, and in compliance with the provisions of this Operating Agreement. However, (a) the Company shall not be required to indemnify the Member for any loss, expense, or damage that the Company may suffer as a result of (i) the Member’s willful misconduct, knowing violation of law, gross negligence, or bad faith; (ii) actions taken by the Member in violation of this Operating Agreement; (iii) the receipt by the Member of a financial benefit to which the Member is not entitled to pursuant to this Operating Agreement or the Act; or (iv) any vote by the Member for a distribution of funds of the Company in violation of this Operating Agreement or the Act; and (b) any liability under this Agreement shall be limited solely to the assets of the Company, and no Member shall have any liability or obligation under this Agreement.</p>
            <h2>ARTICLE IX
                DISSOLUTION AND WINDING UP
            </h2>
            <p><b>9.1 Dissolution.</b> The Company shall be dissolved and its affairs wound up on the first to occur of (a) the time, if any, specified in the Articles; (b) the happening of the event, if any, specified in the Articles; (c) the affirmative unanimous vote of the Members to dissolve the Company; or (d) the entry of a decree of judicial dissolution. On the dissolution of the Company, the Managers shall promptly commence the winding up of the Company’s business and affairs pursuant to and in accordance with the Act. All Company assets remaining after payment to creditors of the Company (including any Members who are creditors) shall be distributed to the Members in accordance with Article IV.

            </p>
            <p><b>9.2 Winding Up.</b> On dissolution, the Company shall cease carrying on its business and affairs and begin to wind them up. The Company shall complete the winding up as soon as practicable. On the winding up of the Company, its assets shall be distributed first to creditors, to the extent permitted by law, in satisfaction of Company debts, liabilities, and obligations (including those owed to Members). The remaining assets shall be distributed as a liquidating distribution to the Members who have positive Capital Accounts, in accordance with their positive Capital Account balances, but only after the Capital Accounts have been adjusted for all prior contributions and distributions and all allocations under Article IV for all periods. The proceeds shall be paid to the Members within 90 days after the date of the winding up.</p>
            <h2>ARTICLE X
                MISCELLANEOUS PROVISIONS
            </h2>
            <p><b>10.1 Terms.</b> Nouns and pronouns will be deemed to refer to the masculine, feminine, neuter, singular, and plural, as the identity of the person, firm, or corporation requires in the context.
            </p>
            <p><b>10.2 Article Headings.</b> The article headings in this Operating Agreement have been inserted only as a matter of convenience and for reference and in no way shall be construed to define, limit, or describe the scope or intent of any provision of this Operating Agreement.</p>
            <p><b>10.3 Counterparts.</b> This Operating Agreement may be executed in several counterparts, each of which will be deemed an original but all of which will constitute one and the same.</p>
            <p><b>10.4 Entire Agreement.</b> This Operating Agreement constitutes the entire agreement among the parties and contains all of the agreements between the parties with respect to the subject matter. This Operating Agreement supersedes all other agreements, either oral or written, between the parties with respect to the subject matter.</p>
            <p><b>10.5 Severability.</b> The invalidity or unenforceability of any particular provision of this Operating Agreement shall not affect the other provisions, and this Operating Agreement shall be construed in all respects as if the invalid or unenforceable provisions were omitted.</p>
            <p><b>10.6 Amendment.</b> This Operating Agreement may be amended or revoked at any time by a written agreement executed by all of the parties to this Operating Agreement. No change or modification to this Operating Agreement shall be valid unless made in writing and signed by all the parties to this Operating Agreement.</p>
            <p><b>10.7 Notices.</b> Any notice permitted or required under this Operating Agreement shall be conveyed to the party at the address reflected in this Operating Agreement and shall be deemed to have been given when deposited in the U.S. mail, postage paid, or when delivered in person, by courier, or by facsimile transmission.</p>
            <p><b>10.8 Binding Effect.</b> Subject to the provisions of this Operating Agreement relating to transferability, this Operating Agreement shall be binding on and shall inure to the benefit of the parties and their respective distributees, heirs, successors, and assigns.</p>
            <p><b>10.9 Conflicts of Interest.</b> THE PARTIES ACKNOWLEDGE THAT LEGAL COUNSEL PREPARING THIS AGREEMENT WAS REPRESENTING THE  COMPANY AND THAT THE MEMBERS (A) HAVE BEEN ADVISED THAT A CONFLICT EXISTS AMONG THEIR INDIVIDUAL INTERESTS; (B) HAVE BEEN ADVISED THAT THEY SHOULD EACH SEEK THE ADVICE OF INDEPENDENT COUNSEL, INCLUDING TAX COUNSEL; AND (C) HAVE EACH HAD THE OPPORTUNITY TO SEEK THE ADVICE OF INDEPENDENT COUNSEL. EACH PARTY WAIVES ANY CLAIMS REGARDING ANY POSSIBLE CONFLICT OF INTEREST WITH REGARD TO THIS AGREEMENT OR ITS PREPARATION.
            </p>
            <p><b>10.10 Governing Law.</b> This Operating Agreement has been executed and delivered in the State of Michigan and shall be governed by and construed and enforced in accordance with the laws of the State of Michigan.</p>

        </>

    )
}



export default Terms;




